name: Lint Python
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Run black
        uses: psf/black@stable
