name: Unit Tests
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          pip install -r .github/requirements.txt
      - name: Run tests
        run: |
          python -m unittest discover
